import { Injectable } from "@angular/core";
import { Workbook } from "exceljs";
import jsPDF from "jspdf";

export interface ReportTable {
  title: string;
  titleAr?: string;
  subtitle: string;
  description?: string;
  columns: string[];
  rows: Array<Array<string | number | boolean | null>>;
  summary: Array<{ label: string; value: string | number }>;
  fileName: string;
  direction?: "rtl" | "ltr";
  locale?: "ar" | "en";
  generatedBy?: string;
  academicYear?: string;
  branch?: string;
  chart?: { labels: string[]; values: number[]; valueKey?: string };
  comparison?: {
    current: number;
    previous: number;
    difference: number;
    percentageChange: number | null;
  } | null;
}

@Injectable({ providedIn: "root" })
export class ReportExportService {
  async downloadExcel(report: ReportTable): Promise<void> {
    const buffer = await this.buildExcel(report);
    this.downloadBlob(
      new Blob([buffer], {
        type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      }),
      `${report.fileName}.xlsx`,
    );
  }

  async buildExcel(report: ReportTable): Promise<Uint8Array> {
    const workbook = new Workbook();
    workbook.creator = "Rawafed ERP";
    workbook.created = new Date();
    const reportSheet = workbook.addWorksheet("Report", {
      views: [
        { showGridLines: false, rightToLeft: report.direction === "rtl" },
      ],
    });
    const dataSheet = workbook.addWorksheet("Data", {
      views: [
        {
          showGridLines: false,
          state: "frozen",
          ySplit: 1,
          rightToLeft: report.direction === "rtl",
        },
      ],
    });
    const checksSheet = workbook.addWorksheet("Checks", {
      views: [
        { showGridLines: false, rightToLeft: report.direction === "rtl" },
      ],
    });
    reportSheet.mergeCells("A1:F2");
    reportSheet.getCell("A1").value =
      report.locale === "ar" && report.titleAr ? report.titleAr : report.title;
    reportSheet.getCell("A1").font = {
      name: "Arial",
      size: 20,
      bold: true,
      color: { argb: "FFFFFFFF" },
    };
    reportSheet.getCell("A1").fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF1D1C50" },
    };
    reportSheet.getCell("A1").alignment = {
      horizontal: "center",
      vertical: "middle",
    };
    reportSheet.mergeCells("A3:F3");
    reportSheet.getCell("A3").value = report.subtitle;
    reportSheet.getCell("A3").alignment = { horizontal: "center" };
    report.summary.forEach((item, index) => {
      const row = 5 + Math.floor(index / 3) * 2;
      const col = 1 + (index % 3) * 2;
      reportSheet.mergeCells(row, col, row, col + 1);
      reportSheet.getCell(row, col).value = item.label;
      reportSheet.getCell(row, col).font = {
        bold: true,
        color: { argb: "FF64748B" },
      };
      reportSheet.mergeCells(row + 1, col, row + 1, col + 1);
      reportSheet.getCell(row + 1, col).value = this.typed(item.value);
      reportSheet.getCell(row + 1, col).font = {
        size: 15,
        bold: true,
        color: { argb: "FF07336B" },
      };
      reportSheet.getCell(row, col).fill = reportSheet.getCell(
        row + 1,
        col,
      ).fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "FFF8FAFC" },
      };
    });
    const start = 6 + Math.ceil(report.summary.length / 3) * 2;
    reportSheet.getCell(start, 1).value = "Generated by";
    reportSheet.getCell(start, 2).value = report.generatedBy || "Rawafed ERP";
    reportSheet.getCell(start + 1, 1).value = "Generated at";
    reportSheet.getCell(start + 1, 2).value = new Date();
    reportSheet.getCell(start + 1, 2).numFmt = "yyyy-mm-dd hh:mm";
    reportSheet.columns = Array.from({ length: 6 }, () => ({ width: 20 }));

    dataSheet.addRow(report.columns);
    report.rows.forEach((row) =>
      dataSheet.addRow(row.map((value) => this.typed(value))),
    );
    const header = dataSheet.getRow(1);
    header.font = { bold: true, color: { argb: "FFFFFFFF" } };
    header.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF1D1C50" },
    };
    header.alignment = { horizontal: "center" };
    dataSheet.columns.forEach((column, columnIndex) => {
      column.width = Math.min(
        32,
        Math.max(
          12,
          ...report.rows
            .slice(0, 100)
            .map(
              (row) => String(row[(column.number || 1) - 1] ?? "").length + 2,
            ),
        ),
      );
      const values = report.rows
        .map((row) => row[columnIndex])
        .filter((value) => value !== null && value !== undefined && value !== "");
      const dateColumn = values.length > 0 && values.every((value) =>
        /^\d{4}-\d{2}-\d{2}(?:[T ][^\s]+)?$/.test(String(value)),
      );
      const numericColumn = values.length > 0 && values.every((value) =>
        typeof value === "number" || /^-?\d+(\.\d+)?$/.test(String(value)),
      );
      column.numFmt = dateColumn
        ? "yyyy-mm-dd"
        : numericColumn
          ? "#,##0.00;[Red](#,##0.00);-"
          : "General";
    });
    dataSheet.autoFilter = {
      from: "A1",
      to: dataSheet.getCell(1, Math.max(report.columns.length, 1)).address,
    };
    checksSheet.addRows([
      ["Check", "Actual", "Expected", "Difference", "Status", "Notes"],
      [
        "Rows exported",
        report.rows.length,
        report.rows.length,
        { formula: "B2-C2" },
        { formula: 'IF(D2=0,"PASS","FAIL")' },
        "Export row-count reconciliation",
      ],
      [
        "Columns exported",
        report.columns.length,
        report.columns.length,
        { formula: "B3-C3" },
        { formula: 'IF(D3=0,"PASS","FAIL")' },
        "Export column-count reconciliation",
      ],
    ]);
    checksSheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } };
    checksSheet.getRow(1).fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF1D1C50" },
    };
    checksSheet.columns = [
      { width: 24 },
      { width: 14 },
      { width: 14 },
      { width: 14 },
      { width: 14 },
      { width: 34 },
    ];
    const buffer = await workbook.xlsx.writeBuffer();
    return new Uint8Array(buffer as ArrayBuffer);
  }

  async downloadPdf(report: ReportTable): Promise<void> {
    const response = await fetch("/fonts/Cairo.ttf");
    if (!response.ok) throw new Error("The Arabic report font could not be loaded.");
    const bytes = await this.buildPdf(report, new Uint8Array(await response.arrayBuffer()));
    this.downloadBlob(new Blob([bytes], { type: "application/pdf" }), `${report.fileName}.pdf`);
  }

  async buildPdf(report: ReportTable, fontBytes: Uint8Array): Promise<Uint8Array> {
    const pdf = new jsPDF({
      unit: "pt",
      format: "a4",
      orientation: report.columns.length > 7 ? "landscape" : "portrait",
      compress: true,
    });
    this.installArabicFont(pdf, fontBytes);
    this.drawVectorReport(pdf, report);
    return new Uint8Array(pdf.output("arraybuffer"));
  }

  private installArabicFont(pdf: jsPDF, bytes: Uint8Array): void {
    let binary = "";
    const chunkSize = 0x8000;
    for (let offset = 0; offset < bytes.length; offset += chunkSize) {
      binary += String.fromCharCode(...bytes.subarray(offset, offset + chunkSize));
    }
    pdf.addFileToVFS("Cairo.ttf", btoa(binary));
    pdf.addFont("Cairo.ttf", "Cairo", "normal");
    pdf.setFont("Cairo", "normal");
  }

  private drawVectorReport(pdf: jsPDF, report: ReportTable): void {
    const rtl = report.direction === "rtl";
    const margin = 36;
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const contentWidth = pageWidth - margin * 2;
    const columnCount = Math.max(report.columns.length, 1);
    const columnWidth = contentWidth / columnCount;
    const rowHeight = 22;
    const headerHeight = 104;
    const footerY = pageHeight - 24;
    let y = headerHeight;

    const drawHeader = (): void => {
      pdf.setFillColor(29, 28, 80);
      pdf.rect(0, 0, pageWidth, 10, "F");
      pdf.setTextColor(29, 28, 80);
      pdf.setFontSize(18);
      this.drawPdfText(
        pdf,
        report.locale === "ar" && report.titleAr ? report.titleAr : report.title,
        rtl ? pageWidth - margin : margin,
        40,
        rtl,
      );
      pdf.setTextColor(71, 85, 105);
      pdf.setFontSize(9);
      this.drawPdfText(pdf, report.subtitle, rtl ? pageWidth - margin : margin, 59, rtl);
      const school = rtl
        ? "مدارس روافد الشرق الأوسط العالمية"
        : "Rawafed International School";
      this.drawPdfText(pdf, school, rtl ? margin : pageWidth - margin, 40, !rtl);
      pdf.setDrawColor(183, 43, 43);
      pdf.setLineWidth(1.5);
      pdf.line(margin, 75, pageWidth - margin, 75);
      pdf.setFillColor(238, 244, 252);
      pdf.rect(margin, 84, contentWidth, 20, "F");
      pdf.setTextColor(11, 55, 111);
      pdf.setFontSize(7.5);
      report.columns.forEach((column, index) => {
        const visualIndex = rtl ? columnCount - 1 - index : index;
        const x = margin + visualIndex * columnWidth;
        this.drawPdfText(
          pdf,
          column,
          rtl ? x + columnWidth - 5 : x + 5,
          97,
          rtl,
        );
      });
    };

    const drawFooter = (): void => {
      pdf.setDrawColor(203, 213, 225);
      pdf.line(margin, footerY - 10, pageWidth - margin, footerY - 10);
      pdf.setTextColor(100, 116, 139);
      pdf.setFontSize(7);
      this.drawPdfText(
        pdf,
        report.generatedBy || "Rawafed ERP",
        rtl ? pageWidth - margin : margin,
        footerY,
        rtl,
      );
      pdf.text(String(pdf.getNumberOfPages()), rtl ? margin : pageWidth - margin, footerY, {
        align: rtl ? "left" : "right",
      });
    };

    drawHeader();
    report.rows.forEach((row, rowIndex) => {
      if (y + rowHeight > footerY - 18) {
        drawFooter();
        pdf.addPage();
        drawHeader();
        y = headerHeight;
      }
      if (rowIndex % 2) {
        pdf.setFillColor(248, 250, 252);
        pdf.rect(margin, y, contentWidth, rowHeight, "F");
      }
      pdf.setTextColor(15, 23, 42);
      pdf.setFontSize(7);
      report.columns.forEach((_, index) => {
        const visualIndex = rtl ? columnCount - 1 - index : index;
        const x = margin + visualIndex * columnWidth;
        const value = String(row[index] ?? "—");
        const clipped = value.length > 34 ? `${value.slice(0, 33)}…` : value;
        this.drawPdfText(
          pdf,
          clipped,
          rtl ? x + columnWidth - 5 : x + 5,
          y + 14,
          rtl,
        );
      });
      pdf.setDrawColor(226, 232, 240);
      pdf.line(margin, y + rowHeight, pageWidth - margin, y + rowHeight);
      y += rowHeight;
    });
    drawFooter();
  }

  private drawPdfText(
    pdf: jsPDF,
    value: unknown,
    x: number,
    y: number,
    rtl: boolean,
  ): void {
    const text = String(value ?? "—");
    const containsArabic = /[\u0600-\u06ff]/.test(text);
    pdf.text(containsArabic ? pdf.processArabic(text) : text, x, y, {
      align: rtl ? "right" : "left",
      baseline: "alphabetic",
    });
  }

  private buildPdfPage(
    report: ReportTable,
    rows: ReportTable["rows"],
    page: number,
    pages: number,
  ): HTMLElement {
    const rtl = report.direction === "rtl";
    const root = document.createElement("section");
    root.dir = rtl ? "rtl" : "ltr";
    root.style.cssText = `position:fixed;left:-10000px;top:0;width:794px;height:1123px;padding:42px 48px;box-sizing:border-box;background:#fff;color:#0f172a;font-family:Arial,"Noto Sans Arabic",sans-serif;overflow:hidden;`;
    root.innerHTML = this.pdfPageHtml(report, rows, page, pages);
    return root;
  }

  pdfPageHtml(
    report: ReportTable,
    rows: ReportTable["rows"],
    page: number,
    pages: number,
  ): string {
    const labels = report.chart?.labels?.slice(0, 10) || [];
    const values = report.chart?.values?.slice(0, 10) || [];
    const max = Math.max(...values.map(Math.abs), 1);
    const chart = labels.length
      ? `<div style="display:flex;align-items:flex-end;gap:10px;height:120px;margin:12px 0 18px;border-bottom:1px solid #cbd5e1;padding:0 8px">${labels.map((label, i) => `<div style="flex:1;text-align:center;min-width:0"><div style="height:${Math.max(3, (Math.abs(values[i] || 0) / max) * 90)}px;background:#0b5ed7;border-radius:5px 5px 0 0"></div><small style="display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:8px">${this.escapeHtml(label)}</small></div>`).join("")}</div>`
      : "";
    const cards = report.summary
      .slice(0, 6)
      .map(
        (item) =>
          `<div style="background:#f8fafc;border:1px solid #dbe3ef;border-radius:8px;padding:9px"><small style="color:#64748b">${this.escapeHtml(item.label)}</small><strong style="display:block;color:#07336b;font-size:15px;margin-top:4px">${this.escapeHtml(item.value)}</strong></div>`,
      )
      .join("");
    return `<header style="display:flex;align-items:center;gap:16px;border-bottom:3px solid #1d1c50;padding-bottom:14px"><img src="/assets/rawafed-logo.png" style="width:64px;height:64px;object-fit:contain"><div style="flex:1"><div style="font-size:12px;color:#64748b">Rawafed International School | مدارس روافد العالمية</div><h1 style="margin:3px 0;color:#1d1c50;font-size:24px">${this.escapeHtml(report.locale === "ar" && report.titleAr ? report.titleAr : report.title)}</h1><div style="font-size:11px;color:#475569">${this.escapeHtml(report.subtitle)}</div></div></header><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:14px 0">${cards}</div>${page === 1 ? chart : ""}<table style="width:100%;border-collapse:collapse;table-layout:fixed;font-size:9px"><thead><tr>${report.columns.map((column) => `<th style="background:#1d1c50;color:#fff;padding:7px 4px;border:1px solid #1d1c50">${this.escapeHtml(column)}</th>`).join("")}</tr></thead><tbody>${rows.map((row, rowIndex) => `<tr style="background:${rowIndex % 2 ? "#f8fafc" : "#fff"}">${report.columns.map((_, i) => `<td style="padding:6px 4px;border-bottom:1px solid #e2e8f0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${this.escapeHtml(row[i])}</td>`).join("")}</tr>`).join("")}</tbody></table><footer style="position:absolute;bottom:26px;left:48px;right:48px;display:flex;justify-content:space-between;border-top:1px solid #cbd5e1;padding-top:8px;color:#64748b;font-size:9px"><span>${this.escapeHtml(report.generatedBy || "Rawafed ERP")} - ${new Date().toLocaleString(report.locale === "ar" ? "ar-SA" : "en-US")}</span><span dir="ltr">${page} / ${pages}</span></footer>`;
  }

  private typed(value: unknown): string | number | boolean | Date | null {
    if (value === null || value === undefined) return null;
    if (typeof value === "number" || typeof value === "boolean") return value;
    const text = String(value);
    if (/^\d{4}-\d{2}-\d{2}$/.test(text))
      return new Date(`${text}T00:00:00.000Z`);
    if (/^-?\d+(\.\d+)?$/.test(text)) return Number(text);
    return text;
  }
  private chunk<T>(rows: T[], size: number): T[][] {
    return Array.from({ length: Math.ceil(rows.length / size) }, (_, index) =>
      rows.slice(index * size, (index + 1) * size),
    );
  }
  private escapeHtml(value: unknown): string {
    return String(value ?? "-").replace(
      /[&<>"']/g,
      (character) =>
        ({
          "&": "&amp;",
          "<": "&lt;",
          ">": "&gt;",
          '"': "&quot;",
          "'": "&#39;",
        })[character]!,
    );
  }
  private downloadBlob(blob: Blob, fileName: string): void {
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = fileName;
    link.click();
    URL.revokeObjectURL(url);
  }
}
