import { Injectable } from "@angular/core";
import { Workbook } from "exceljs";
import jsPDF from "jspdf";

export interface ReportTable {
  title: string;
  titleAr?: string;
  subtitle: string;
  description?: string;
  columns: string[];
  rows: Array<Array<string | number | boolean | null>>;
  summary: Array<{ label: string; value: string | number }>;
  fileName: string;
  direction?: "rtl" | "ltr";
  locale?: "ar" | "en";
  generatedBy?: string;
  academicYear?: string;
  branch?: string;
  chart?: { labels: string[]; values: number[]; valueKey?: string };
  comparison?: {
    current: number;
    previous: number;
    difference: number;
    percentageChange: number | null;
  } | null;
}

@Injectable({ providedIn: "root" })
export class ReportExportService {
  async downloadExcel(report: ReportTable): Promise<void> {
    const buffer = await this.buildExcel(report);
    this.downloadBlob(
      new Blob([buffer], {
        type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      }),
      `${report.fileName}.xlsx`,
    );
  }

  async buildExcel(report: ReportTable): Promise<Uint8Array> {
    const workbook = new Workbook();
    workbook.creator = "Rawafed ERP";
    workbook.created = new Date();
    const reportSheet = workbook.addWorksheet("Report", {
      views: [
        { showGridLines: false, rightToLeft: report.direction === "rtl" },
      ],
    });
    const dataSheet = workbook.addWorksheet("Data", {
      views: [
        {
          showGridLines: false,
          state: "frozen",
          ySplit: 1,
          rightToLeft: report.direction === "rtl",
        },
      ],
    });
    const checksSheet = workbook.addWorksheet("Checks", {
      views: [
        { showGridLines: false, rightToLeft: report.direction === "rtl" },
      ],
    });
    reportSheet.mergeCells("A1:F2");
    reportSheet.getCell("A1").value =
      report.locale === "ar" && report.titleAr ? report.titleAr : report.title;
    reportSheet.getCell("A1").font = {
      name: "Arial",
      size: 20,
      bold: true,
      color: { argb: "FFFFFFFF" },
    };
    reportSheet.getCell("A1").fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF1D1C50" },
    };
    reportSheet.getCell("A1").alignment = {
      horizontal: "center",
      vertical: "middle",
    };
    reportSheet.mergeCells("A3:F3");
    reportSheet.getCell("A3").value = report.subtitle;
    reportSheet.getCell("A3").alignment = { horizontal: "center" };
    report.summary.forEach((item, index) => {
      const row = 5 + Math.floor(index / 3) * 2;
      const col = 1 + (index % 3) * 2;
      reportSheet.mergeCells(row, col, row, col + 1);
      reportSheet.getCell(row, col).value = item.label;
      reportSheet.getCell(row, col).font = {
        bold: true,
        color: { argb: "FF64748B" },
      };
      reportSheet.mergeCells(row + 1, col, row + 1, col + 1);
      reportSheet.getCell(row + 1, col).value = this.typed(item.value);
      reportSheet.getCell(row + 1, col).font = {
        size: 15,
        bold: true,
        color: { argb: "FF07336B" },
      };
      reportSheet.getCell(row, col).fill = reportSheet.getCell(
        row + 1,
        col,
      ).fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "FFF8FAFC" },
      };
    });
    const start = 6 + Math.ceil(report.summary.length / 3) * 2;
    reportSheet.getCell(start, 1).value = "Generated by";
    reportSheet.getCell(start, 2).value = report.generatedBy || "Rawafed ERP";
    reportSheet.getCell(start + 1, 1).value = "Generated at";
    reportSheet.getCell(start + 1, 2).value = new Date();
    reportSheet.getCell(start + 1, 2).numFmt = "yyyy-mm-dd hh:mm";
    reportSheet.columns = Array.from({ length: 6 }, () => ({ width: 20 }));

    dataSheet.addRow(report.columns);
    report.rows.forEach((row) =>
      dataSheet.addRow(row.map((value) => this.typed(value))),
    );
    const header = dataSheet.getRow(1);
    header.font = { bold: true, color: { argb: "FFFFFFFF" } };
    header.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF1D1C50" },
    };
    header.alignment = { horizontal: "center" };
    dataSheet.columns.forEach((column, columnIndex) => {
      column.width = Math.min(
        32,
        Math.max(
          12,
          ...report.rows
            .slice(0, 100)
            .map(
              (row) => String(row[(column.number || 1) - 1] ?? "").length + 2,
            ),
        ),
      );
      const values = report.rows
        .map((row) => row[columnIndex])
        .filter((value) => value !== null && value !== undefined && value !== "");
      const dateColumn = values.length > 0 && values.every((value) =>
        /^\d{4}-\d{2}-\d{2}(?:[T ][^\s]+)?$/.test(String(value)),
      );
      const numericColumn = values.length > 0 && values.every((value) =>
        typeof value === "number" || /^-?\d+(\.\d+)?$/.test(String(value)),
      );
      column.numFmt = dateColumn
        ? "yyyy-mm-dd"
        : numericColumn
          ? "#,##0.00;[Red](#,##0.00);-"
          : "General";
    });
    dataSheet.autoFilter = {
      from: "A1",
      to: dataSheet.getCell(1, Math.max(report.columns.length, 1)).address,
    };
    checksSheet.addRows([
      ["Check", "Actual", "Expected", "Difference", "Status", "Notes"],
      [
        "Rows exported",
        report.rows.length,
        report.rows.length,
        { formula: "B2-C2" },
        { formula: 'IF(D2=0,"PASS","FAIL")' },
        "Export row-count reconciliation",
      ],
      [
        "Columns exported",
        report.columns.length,
        report.columns.length,
        { formula: "B3-C3" },
        { formula: 'IF(D3=0,"PASS","FAIL")' },
        "Export column-count reconciliation",
      ],
    ]);
    checksSheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } };
    checksSheet.getRow(1).fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF1D1C50" },
    };
    checksSheet.columns = [
      { width: 24 },
      { width: 14 },
      { width: 14 },
      { width: 14 },
      { width: 14 },
      { width: 34 },
    ];
    const buffer = await workbook.xlsx.writeBuffer();
    return new Uint8Array(buffer as ArrayBuffer);
  }

  async downloadPdf(report: ReportTable): Promise<void> {
    const [fontResponse, logoResponse] = await Promise.all([
      fetch("/fonts/Amiri-Regular.ttf"),
      fetch("/assets/rawafed-logo.png"),
    ]);
    if (!fontResponse.ok)
      throw new Error("The Arabic report font could not be loaded.");
    const bytes = await this.buildPdf(
      report,
      new Uint8Array(await fontResponse.arrayBuffer()),
      logoResponse.ok ? new Uint8Array(await logoResponse.arrayBuffer()) : null,
    );
    this.downloadBlob(new Blob([bytes], { type: "application/pdf" }), `${report.fileName}.pdf`);
  }

  async printPdf(report: ReportTable): Promise<void> {
    const [fontResponse, logoResponse] = await Promise.all([
      fetch("/fonts/Amiri-Regular.ttf"),
      fetch("/assets/rawafed-logo.png"),
    ]);
    if (!fontResponse.ok)
      throw new Error("The Arabic report font could not be loaded.");
    const bytes = await this.buildPdf(
      report,
      new Uint8Array(await fontResponse.arrayBuffer()),
      logoResponse.ok ? new Uint8Array(await logoResponse.arrayBuffer()) : null,
    );
    const url = URL.createObjectURL(new Blob([bytes], { type: "application/pdf" }));
    const popup = window.open(url, "_blank");
    if (!popup) {
      URL.revokeObjectURL(url);
      throw new Error("تعذر فتح نافذة الطباعة. يرجى السماح بالنوافذ المنبثقة.");
    }
    popup.opener = null;
    popup.addEventListener("load", () => popup.print(), { once: true });
    window.setTimeout(() => URL.revokeObjectURL(url), 60_000);
  }

  async buildPdf(
    report: ReportTable,
    fontBytes: Uint8Array,
    logoBytes: Uint8Array | null = null,
  ): Promise<Uint8Array> {
    const pdf = new jsPDF({
      unit: "pt",
      format: "a4",
      orientation: report.columns.length > 7 ? "landscape" : "portrait",
      compress: true,
    });
    this.installArabicFont(pdf, fontBytes);
    this.drawVectorReport(pdf, report, logoBytes);
    return new Uint8Array(pdf.output("arraybuffer"));
  }

  private installArabicFont(pdf: jsPDF, bytes: Uint8Array): void {
    let binary = "";
    const chunkSize = 0x8000;
    for (let offset = 0; offset < bytes.length; offset += chunkSize) {
      binary += String.fromCharCode(...bytes.subarray(offset, offset + chunkSize));
    }
    pdf.addFileToVFS("Amiri-Regular.ttf", btoa(binary));
    pdf.addFont("Amiri-Regular.ttf", "Amiri", "normal");
    pdf.setFont("Amiri", "normal");
  }

  private drawVectorReport(
    pdf: jsPDF,
    report: ReportTable,
    logoBytes: Uint8Array | null,
  ): void {
    const rtl = report.direction === "rtl";
    const margin = 32;
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const contentWidth = pageWidth - margin * 2;
    const widths = this.reportColumnWidths(pdf, report, contentWidth);
    const footerY = pageHeight - 31;
    let y = 0;

    const drawIdentityHeader = (): void => {
      pdf.setFillColor(29, 28, 80);
      pdf.rect(0, 0, pageWidth, 12, "F");
      pdf.setFillColor(190, 47, 47);
      pdf.rect(rtl ? 0 : pageWidth - 125, 12, 125, 5, "F");
      if (logoBytes) {
        try {
          pdf.addImage(
            this.bytesDataUrl(logoBytes, "image/png"),
            "PNG",
            rtl ? pageWidth - margin - 48 : margin,
            24,
            48,
            48,
            undefined,
            "FAST",
          );
        } catch {
          // A missing or corrupt logo must not prevent the financial report export.
        }
      }
      pdf.setTextColor(29, 28, 80);
      pdf.setFontSize(17);
      this.drawPdfText(
        pdf,
        report.locale === "ar" && report.titleAr ? report.titleAr : report.title,
        rtl ? margin : pageWidth - margin,
        39,
        !rtl,
      );
      pdf.setFontSize(10.5);
      this.drawPdfText(
        pdf,
        rtl ? "مدارس روافد الشرق الأوسط العالمية" : "Rawafed International School",
        rtl ? pageWidth - margin - 58 : margin + 58,
        37,
        rtl,
      );
      pdf.setTextColor(71, 85, 105);
      pdf.setFontSize(9);
      this.drawPdfText(
        pdf,
        rtl
          ? "الرياض، حي الخليج، شارع بحر العرب"
          : "Riyadh, Al Khaleej District, Bahr Al Arab Street",
        rtl ? pageWidth - margin - 58 : margin + 58,
        51,
        rtl,
      );
      this.drawPdfText(pdf, report.subtitle, rtl ? margin : pageWidth - margin, 58, !rtl);
      pdf.setDrawColor(183, 43, 43);
      pdf.setLineWidth(1.5);
      pdf.line(margin, 82, pageWidth - margin, 82);
      y = 94;
    };

    const drawTableHeader = (): void => {
      const headerLines = report.columns.map((column, index) =>
        this.wrappedPdfText(pdf, column, Math.max(widths[index] - 10, 12)),
      );
      const headerHeight = Math.max(25, ...headerLines.map((lines) => lines.length * 9 + 10));
      pdf.setFillColor(238, 244, 252);
      pdf.rect(margin, y, contentWidth, headerHeight, "F");
      pdf.setTextColor(11, 55, 111);
      pdf.setFontSize(7.5);
      let offset = 0;
      report.columns.forEach((_column, index) => {
        const cellX = rtl ? pageWidth - margin - offset - widths[index] : margin + offset;
        this.drawWrappedCell(pdf, headerLines[index], cellX, y, widths[index], headerHeight, rtl);
        offset += widths[index];
      });
      this.drawTableGrid(pdf, y, headerHeight, widths, rtl, pageWidth, margin);
      y += headerHeight;
    };

    const drawSummary = (): void => {
      const items = report.summary.slice(0, 6);
      if (!items.length) return;
      const columns = Math.min(items.length, 3);
      const cardWidth = (contentWidth - (columns - 1) * 8) / columns;
      items.forEach((item, index) => {
        const row = Math.floor(index / columns);
        const visualColumn = rtl ? columns - 1 - (index % columns) : index % columns;
        const x = margin + visualColumn * (cardWidth + 8);
        const top = y + row * 45;
        pdf.setFillColor(248, 250, 252);
        pdf.setDrawColor(219, 227, 239);
        pdf.roundedRect(x, top, cardWidth, 37, 4, 4, "FD");
        pdf.setTextColor(100, 116, 139);
        pdf.setFontSize(7);
        this.drawPdfText(pdf, item.label, rtl ? x + cardWidth - 7 : x + 7, top + 12, rtl);
        pdf.setTextColor(7, 51, 107);
        pdf.setFontSize(11);
        this.drawPdfText(pdf, item.value, rtl ? x + cardWidth - 7 : x + 7, top + 29, rtl);
      });
      y += Math.ceil(items.length / columns) * 45 + 4;
    };

    const drawChart = (): void => {
      const labels = report.chart?.labels?.slice(0, 12) || [];
      const values = report.chart?.values?.slice(0, labels.length) || [];
      if (!labels.length || !values.length) return;
      const chartHeight = 82;
      const baseline = y + chartHeight - 18;
      const max = Math.max(...values.map((value) => Math.abs(Number(value) || 0)), 1);
      const slot = contentWidth / labels.length;
      pdf.setDrawColor(203, 213, 225);
      pdf.line(margin, baseline, pageWidth - margin, baseline);
      labels.forEach((label, index) => {
        const value = Number(values[index] || 0);
        const barHeight = Math.max(2, (Math.abs(value) / max) * (chartHeight - 34));
        const x = margin + index * slot + slot * 0.2;
        pdf.setFillColor(20, 86, 157);
        pdf.roundedRect(x, baseline - barHeight, slot * 0.6, barHeight, 2, 2, "F");
        pdf.setFontSize(6.5);
        pdf.setTextColor(15, 23, 42);
        pdf.text(this.localizedNumber(value, report.locale), x + slot * 0.3, baseline - barHeight - 3, { align: "center" });
        const labelLines = this.wrappedPdfText(pdf, label, slot - 4).slice(0, 2);
        labelLines.forEach((line, lineIndex) =>
          pdf.text(line, x + slot * 0.3, baseline + 8 + lineIndex * 7, { align: "center" }),
        );
      });
      y += chartHeight + 6;
    };

    drawIdentityHeader();
    drawSummary();
    drawChart();
    drawTableHeader();
    report.rows.forEach((row, rowIndex) => {
      const cellLines = report.columns.map((_column, index) =>
        this.wrappedPdfText(pdf, row[index] ?? "—", Math.max(widths[index] - 10, 12)),
      );
      const rowHeight = Math.max(23, ...cellLines.map((lines) => lines.length * 9 + 10));
      if (y + rowHeight > footerY - 12) {
        pdf.addPage();
        drawIdentityHeader();
        drawTableHeader();
      }
      if (rowIndex % 2) {
        pdf.setFillColor(248, 250, 252);
        pdf.rect(margin, y, contentWidth, rowHeight, "F");
      }
      pdf.setTextColor(15, 23, 42);
      pdf.setFontSize(7);
      let offset = 0;
      report.columns.forEach((_, index) => {
        const cellX = rtl ? pageWidth - margin - offset - widths[index] : margin + offset;
        this.drawWrappedCell(pdf, cellLines[index], cellX, y, widths[index], rowHeight, rtl);
        offset += widths[index];
      });
      this.drawTableGrid(pdf, y, rowHeight, widths, rtl, pageWidth, margin);
      y += rowHeight;
    });
    const pages = pdf.getNumberOfPages();
    for (let page = 1; page <= pages; page += 1) {
      pdf.setPage(page);
      pdf.setDrawColor(203, 213, 225);
      pdf.line(margin, footerY - 10, pageWidth - margin, footerY - 10);
      pdf.setTextColor(100, 116, 139);
      pdf.setFontSize(7);
      this.drawPdfText(pdf, report.generatedBy || "Rawafed ERP", rtl ? pageWidth - margin : margin, footerY, rtl);
      pdf.text(`${page} / ${pages}`, rtl ? margin : pageWidth - margin, footerY, { align: rtl ? "left" : "right" });
    }
  }

  private reportColumnWidths(pdf: jsPDF, report: ReportTable, contentWidth: number): number[] {
    pdf.setFontSize(7);
    const weights = report.columns.map((column, index) => {
      const samples = [column, ...report.rows.slice(0, 80).map((row) => String(row[index] ?? ""))];
      const longest = Math.max(...samples.map((value) => Math.min(pdf.getTextWidth(this.preparedPdfText(pdf, value)), 150)), 18);
      return Math.max(28, longest + 12);
    });
    const sum = weights.reduce((total, value) => total + value, 0) || 1;
    return weights.map((weight) => (weight / sum) * contentWidth);
  }

  private wrappedPdfText(pdf: jsPDF, value: unknown, maxWidth: number): string[] {
    return pdf.splitTextToSize(this.preparedPdfText(pdf, value), maxWidth) as string[];
  }

  private preparedPdfText(pdf: jsPDF, value: unknown): string {
    const text = String(value ?? "—");
    return /[\u0600-\u06ff]/.test(text) ? pdf.processArabic(text) : text;
  }

  private drawWrappedCell(
    pdf: jsPDF,
    lines: string[],
    x: number,
    y: number,
    width: number,
    height: number,
    rtl: boolean,
  ): void {
    const lineHeight = 9;
    const startY = y + Math.max(10, (height - lines.length * lineHeight) / 2 + 7);
    lines.forEach((line, index) =>
      pdf.text(line, rtl ? x + width - 5 : x + 5, startY + index * lineHeight, {
        align: rtl ? "right" : "left",
      }),
    );
  }

  private drawTableGrid(
    pdf: jsPDF,
    y: number,
    height: number,
    widths: number[],
    rtl: boolean,
    pageWidth: number,
    margin: number,
  ): void {
    pdf.setDrawColor(220, 228, 238);
    pdf.setLineWidth(0.35);
    pdf.line(margin, y + height, pageWidth - margin, y + height);
    let offset = 0;
    widths.slice(0, -1).forEach((width) => {
      offset += width;
      const x = rtl ? pageWidth - margin - offset : margin + offset;
      pdf.line(x, y, x, y + height);
    });
  }

  private drawPdfText(
    pdf: jsPDF,
    value: unknown,
    x: number,
    y: number,
    rtl: boolean,
  ): void {
    pdf.text(this.preparedPdfText(pdf, value), x, y, {
      align: rtl ? "right" : "left",
      baseline: "alphabetic",
    });
  }

  private localizedNumber(value: number, locale: ReportTable["locale"]): string {
    return new Intl.NumberFormat(locale === "ar" ? "ar-SA" : "en-US", {
      maximumFractionDigits: 2,
    }).format(value);
  }

  private bytesDataUrl(bytes: Uint8Array, mime: string): string {
    let binary = "";
    for (let offset = 0; offset < bytes.length; offset += 0x8000)
      binary += String.fromCharCode(...bytes.subarray(offset, offset + 0x8000));
    return `data:${mime};base64,${btoa(binary)}`;
  }

  private buildPdfPage(
    report: ReportTable,
    rows: ReportTable["rows"],
    page: number,
    pages: number,
  ): HTMLElement {
    const rtl = report.direction === "rtl";
    const root = document.createElement("section");
    root.dir = rtl ? "rtl" : "ltr";
    root.style.cssText = `position:fixed;left:-10000px;top:0;width:794px;height:1123px;padding:42px 48px;box-sizing:border-box;background:#fff;color:#0f172a;font-family:Arial,"Noto Sans Arabic",sans-serif;overflow:hidden;`;
    root.innerHTML = this.pdfPageHtml(report, rows, page, pages);
    return root;
  }

  pdfPageHtml(
    report: ReportTable,
    rows: ReportTable["rows"],
    page: number,
    pages: number,
  ): string {
    const labels = report.chart?.labels?.slice(0, 10) || [];
    const values = report.chart?.values?.slice(0, 10) || [];
    const max = Math.max(...values.map(Math.abs), 1);
    const chart = labels.length
      ? `<div style="display:flex;align-items:flex-end;gap:10px;height:120px;margin:12px 0 18px;border-bottom:1px solid #cbd5e1;padding:0 8px">${labels.map((label, i) => `<div style="flex:1;text-align:center;min-width:0"><div style="height:${Math.max(3, (Math.abs(values[i] || 0) / max) * 90)}px;background:#0b5ed7;border-radius:5px 5px 0 0"></div><small style="display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:8px">${this.escapeHtml(label)}</small></div>`).join("")}</div>`
      : "";
    const cards = report.summary
      .slice(0, 6)
      .map(
        (item) =>
          `<div style="background:#f8fafc;border:1px solid #dbe3ef;border-radius:8px;padding:9px"><small style="color:#64748b">${this.escapeHtml(item.label)}</small><strong style="display:block;color:#07336b;font-size:15px;margin-top:4px">${this.escapeHtml(item.value)}</strong></div>`,
      )
      .join("");
    return `<header style="display:flex;align-items:center;gap:16px;border-bottom:3px solid #1d1c50;padding-bottom:14px"><img src="/assets/rawafed-logo.png" style="width:64px;height:64px;object-fit:contain"><div style="flex:1"><div style="font-size:12px;color:#64748b">Rawafed International School | مدارس روافد العالمية</div><h1 style="margin:3px 0;color:#1d1c50;font-size:24px">${this.escapeHtml(report.locale === "ar" && report.titleAr ? report.titleAr : report.title)}</h1><div style="font-size:11px;color:#475569">${this.escapeHtml(report.subtitle)}</div></div></header><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:14px 0">${cards}</div>${page === 1 ? chart : ""}<table style="width:100%;border-collapse:collapse;table-layout:fixed;font-size:9px"><thead><tr>${report.columns.map((column) => `<th style="background:#1d1c50;color:#fff;padding:7px 4px;border:1px solid #1d1c50">${this.escapeHtml(column)}</th>`).join("")}</tr></thead><tbody>${rows.map((row, rowIndex) => `<tr style="background:${rowIndex % 2 ? "#f8fafc" : "#fff"}">${report.columns.map((_, i) => `<td style="padding:6px 4px;border-bottom:1px solid #e2e8f0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${this.escapeHtml(row[i])}</td>`).join("")}</tr>`).join("")}</tbody></table><footer style="position:absolute;bottom:26px;left:48px;right:48px;display:flex;justify-content:space-between;border-top:1px solid #cbd5e1;padding-top:8px;color:#64748b;font-size:9px"><span>${this.escapeHtml(report.generatedBy || "Rawafed ERP")} - ${new Date().toLocaleString(report.locale === "ar" ? "ar-SA" : "en-US")}</span><span dir="ltr">${page} / ${pages}</span></footer>`;
  }

  private typed(value: unknown): string | number | boolean | Date | null {
    if (value === null || value === undefined) return null;
    if (typeof value === "number" || typeof value === "boolean") return value;
    const text = String(value);
    if (/^\d{4}-\d{2}-\d{2}$/.test(text))
      return new Date(`${text}T00:00:00.000Z`);
    if (/^-?\d+(\.\d+)?$/.test(text)) return Number(text);
    return text;
  }
  private chunk<T>(rows: T[], size: number): T[][] {
    return Array.from({ length: Math.ceil(rows.length / size) }, (_, index) =>
      rows.slice(index * size, (index + 1) * size),
    );
  }
  private escapeHtml(value: unknown): string {
    return String(value ?? "-").replace(
      /[&<>"']/g,
      (character) =>
        ({
          "&": "&amp;",
          "<": "&lt;",
          ">": "&gt;",
          '"': "&quot;",
          "'": "&#39;",
        })[character]!,
    );
  }
  private downloadBlob(blob: Blob, fileName: string): void {
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = fileName;
    link.click();
    URL.revokeObjectURL(url);
  }
}
