import { Routes } from '@angular/router';

export const financeRoutes: Routes = [
  { path: '', loadComponent: () => import('./dashboard/dashboard').then((m) => m.Dashboard) },
  { path: 'dashboard', loadComponent: () => import('./dashboard/dashboard').then((m) => m.Dashboard) },
  { path: 'patient-packages', loadComponent: () => import('./patient-packages/patient-packages').then((m) => m.PatientPackages) },
  { path: 'payments', loadComponent: () => import('./payments/payments').then((m) => m.Payments) },
  { path: 'reports', loadComponent: () => import('./reports/reports').then((m) => m.Reports) },
  { path: 'accounting', loadComponent: () => import('./accounting-erp/accounting-erp').then((m) => m.AccountingErp) },
  { path: 'inventory', loadComponent: () => import('./inventory-erp/inventory-erp').then((m) => m.InventoryErp) },
  { path: 'customers', loadComponent: () => import('./customers/customers').then((m) => m.Customers) },
  { path: 'customers/:id', loadComponent: () => import('./customer-profile/customer-profile').then((m) => m.CustomerProfile) },
  { path: 'chart-of-accounts', loadComponent: () => import('./chart-of-accounts/chart-of-accounts').then((m) => m.ChartOfAccounts) },
  { path: 'fixed-assets', loadComponent: () => import('./fixed-assets/fixed-assets').then((m) => m.FixedAssets) },
  { path: 'cashboxes', loadComponent: () => import('./cashboxes/cashboxes').then((m) => m.Cashboxes) },
  { path: 'banks', loadComponent: () => import('./banks/banks').then((m) => m.Banks) },
  { path: 'suppliers', loadComponent: () => import('./suppliers/suppliers').then((m) => m.Suppliers) },
  { path: 'suppliers/:id', loadComponent: () => import('./supplier-profile/supplier-profile').then((m) => m.SupplierProfile) },
  { path: 'add-package', loadComponent: () => import('./add-package/add-package').then((m) => m.AddPackage) },
  { path: 'add-package/:id', loadComponent: () => import('./add-package/add-package').then((m) => m.AddPackage) },
  { path: 'package-details/:id', loadComponent: () => import('./package-details/package-details').then((m) => m.PackageDetails) },
  { path: 'add-payment', loadComponent: () => import('./add-payment/add-payment').then((m) => m.AddPayment) },
  { path: 'payment-details/:id', loadComponent: () => import('./payment-details/payment-details').then((m) => m.PaymentDetails) },
  { path: 'edit-package/:id', loadComponent: () => import('./edit-package/edit-package').then((m) => m.EditPackage) },
  { path: 'expenses', loadComponent: () => import('./expenses/expenses').then((m) => m.Expenses) },
  { path: 'add-expense', loadComponent: () => import('./add-expense/add-expense').then((m) => m.AddExpense) },
  { path: 'expense-details', loadComponent: () => import('./expense-details/expense-details').then((m) => m.ExpenseDetails) },
  { path: 'expense-details/:id', loadComponent: () => import('./expense-details/expense-details').then((m) => m.ExpenseDetails) },
  { path: 'invoices', loadComponent: () => import('./invoices/invoices').then((m) => m.Invoices) },
  { path: 'invoice-details/:id', loadComponent: () => import('./invoice-details/invoice-details').then((m) => m.InvoiceDetails) },
  { path: 'edit-invoice/:id', loadComponent: () => import('./edit-invoice/edit-invoice').then((m) => m.EditInvoice) },
  { path: 'edit-expense/:id', loadComponent: () => import('./edit-expense/edit-expense').then((m) => m.EditExpense) },
  { path: 'doctors', loadComponent: () => import('./doctors/doctors').then((m) => m.Doctors) },
  { path: 'add-staff', loadComponent: () => import('./add-doctor/add-doctor').then((m) => m.AddDoctor) },
  { path: 'doctor-details/:id', loadComponent: () => import('./doctor-details/doctor-details').then((m) => m.DoctorDetails) },
  { path: 'edit-doctor/:id', loadComponent: () => import('./edit-doctor/edit-doctor').then((m) => m.EditDoctor) },
  { path: 'payroll', loadComponent: () => import('./payroll/payroll').then((m) => m.Payroll) },
  { path: 'salary-processing', loadComponent: () => import('./salary-processing/salary-processing').then((m) => m.SalaryProcessing) },
  { path: 'employee-details/:id', loadComponent: () => import('./employee-details/employee-details').then((m) => m.EmployeeDetails) },
  { path: 'add-doctor', loadComponent: () => import('./add-doctor/add-doctor').then((m) => m.AddDoctor) },
  { path: 'patients', loadComponent: () => import('./patients/patients').then((m) => m.Patients) },
  { path: 'patient-details/:id', loadComponent: () => import('./patient-details/patient-details').then((m) => m.PatientDetails) },
  { path: 'add-patient', loadComponent: () => import('./add-patient/add-patient').then((m) => m.AddPatient) },
  { path: 'edit-patient/:id', loadComponent: () => import('./add-patient/add-patient').then((m) => m.AddPatient) },
  { path: 'generate-invoice', loadComponent: () => import('./generate-invoice/generate-invoice').then((m) => m.GenerateInvoice) }
];
